on: push
jobs:
  Build_Project:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: javac *.java
  Run_Basic_IO_Tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: javac *.java
      - run: java Main < test/test1.txt
      - run: java Main < test/test2.txt
      - run: java Main < test/test3.txt
      - run: java Main < test/test4.txt
      - run: java Main < test/test5.txt
      - run: java Main < test/test6.txt
      - run: java Main < test/test7.txt
