name: Continuous Integration

on: push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-java@v2
      with:
        distribution: "adopt"
        java-version: "11"

    - name: Check
      run: gradlew check

    - name: Install
      run: gradlew installDist

    - name: CLI tests
      shell: bash
      env: { APP: app/build/install/app/bin/app }
      run: |
        for test in "$(ls test/*.txt)"; do
          $APP < $test > $test.generated
          diff $test.generated $test.txt.out
        done

        $APP test/test8.json test/test9.json > test/test8.generated
        diff test/test8.generated test/test8.txt.out

        ! $APP test/test8.json

        $APP test/test8.json test/test9.json > test/test10.generated
        diff test/test10.generated test/test10.txt.out

        $APP test/test9.json test/test10.json > test/test11.generated
        diff test/test11.generated test/test11.txt.out
