name: Continuous Integration

on: push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-java@v2
      with:
        distribution: "adopt"
        java-version: "11"

    - name: Gradle
      uses: burrunan/gradle-cache-action@v1
      with: { arguments: check installDist }

    - name: CLI tests
      shell: bash
      env: { APP: app/build/install/app/bin/app }
      run: |
        "$APP" < test/test1.txt | grep -qEe '^A won!'
        "$APP" < test/test2.txt | grep -qEe '^There wouldn'
        "$APP" < test/test3.txt | grep -qEe '^Unbalanced combat! B won!'
        "$APP" < test/test4.txt | grep -qEe '^There wouldn'
        "$APP" < test/test5.txt | grep -qEe '^Both heroes are dead!'
        "$APP" test/test8.json test/test9.json | grep -qEe '^Bob won!'
        ! "$APP" test/test8.json
        "$APP" test/test9.json test/test9.json | grep -qEe '^Bob won!'
        "$APP" test/test9.json test/test10.json | grep -qEe '^Max won!'
